### ISSUE TITLE
Thoughts on "unreasonable effectiveness"

### ISSUE THREAD

**Issue by hadley** [STAT545-UBC/STAT545-UBC.github.io#17]
* It might be cool to show people how to add an "edit this page" link. This has been great way of getting improvements to the r-pkgs/adv-r books.

* I think I've finally figured out a workflow that will support this same scenario for vignettes. I just have to find the time to implement it (it needs some changes to `devtools::install()`)

* I think there are also benefits to checking in rendered .md and .png when you look at diffs - you also get see how the outputs changed, not just how the inputs changed

**Comment by jennybc** [comment]
These are all great ideas!

I'm very interested in the right way to have a compiled vignette show up somewhere on GitHub automagically in a hosted package that's being documented, checked, and built regularly. A browsability "win" for the subset of repos that are also R packages.

Yeah, I should add a screenshot from GitHub or SourceTree showing diffs of, e.g. PNGs, because it's great example version control payoff. These points are actually wandering into related territory, which is how to make GitHub work for you as a data analyst.

**Comment by hadley** [comment]
I think that should be the job of travis + staticdocs or similar, I just haven't had the time to spend on it lately.

**Comment by jennybc** [comment]
Maybe that will be a nice thing to add once the dust settles re: R-native Travis thing (https://staging.travis-ci.org/craigcitro/r-travis/builds/428427). Would vignette creation and publishing be something one can activate via the `devtools::use_travis()` function?

**Comment by hadley** [comment]
I don't think it will be built into `devtools::use_travis()` but it might be an additional helper function. I just need to figure out a robust process before encoding it in a function.
