### ISSUE TITLE
Gitbook Testing

### ISSUE THREAD

**Issue by npjc** [STAT545-UBC/STAT545-UBC.github.io#29]
@jennybc @STAT545-UBC/2015_ta 

First preview the thingy [here](https://htmlpreview.github.io/?https://github.com/npjc/STAT545-UBC.github.io/blob/gitbook-play/zzz_gitbook-website-play/_book/index.html).
### what

On the [gitbook-play branch](https://github.com/npjc/STAT545-UBC.github.io/tree/gitbook-play) of my fork of the website I've pushed a really quick and dirty [gitbook](https://www.gitbook.com/) static website version of the markdown content of the website.

Basically all the slug-headed files were copied into their own sub directory and used the `.md` files within to generate a set of links which is what gitbook uses to build the site. more [here](https://github.com/npjc/STAT545-UBC.github.io/tree/gitbook-play/zzz_gitbook-website-play).

This is just a really rough test -- I wanted to see if I could do it quickly (I had been looking at gitbook for a while and thought it was neat but never took the time/had a use case -- and then I read @daattali suggesting it in an issue I think (but I can't find where now...).
### takeaway

This tool is trivially easy to use.

if there is someone with the knowledge of _how_ the website should be laid out (sectioned) etc.. then:
- is it the right tool for the job?
- If so then it's a matter of refactoring the directory structures. (This would also involve mega linkedy overhaul/simplification)
- One site / multiple ones?
### tidbits
- there is also the [Rgitbook pkg](https://github.com/jbryer/Rgitbook) which wraps the cli but it gave me some grief (and hasn't been active in a year or so) so for now I'd stick with the cli itself.
- could also auto-incorporate an edit-this-page button which follows this kind of link (that I remember from reading another issue -- though again I am useless at finding it currently):

https://github.com/organisation/repo/edit/master/section/file.md

**Comment by jennybc** [comment]
OMG this is very exciting! :tada: Thank you so much for having a crack at this! I would love to get this content such that it makes a nicer website and a book. From my brief preview, this looks more like the former? Which is of great interest. We need to think about whether this should just become the future layout of the website ... I'm guessing yes?

This still leave the leanpub idea, which would produce a more conventional book.

Who is interested in this stuff besides @npjc and me? We should get together to dicuss.

**Comment by daattali** [comment]
@npjc thanks for getting us started on this! I just looked into the different options a bit as well, and I spent a bit of time seeing what can be done with gitbook and leanpub (since they seem to be the most popular ones that everyone mentions).

The only benefit IMO that LeanPub offers over GitBook is that leanpub takes 10% of any sales while gitbook takes 20%.

**gitbook**
[I made a version available here](https://www.gitbook.com/book/daattali/stat545-ubc-github-io/details)
- Super easy to get started
- documentation is simple, short, and useful
- it just works!
- every time a git commit is made, the book is ready in about 1 minute
- very trivial to transform our repo into a book: it expects .md files (which is what we have) and we just need to create a file 
- perfect integration with github
- bonus nice feature: shows traffic history
- by default the "book" is a "website" that just takes one click to start browsing, but users can download a pdf version easily as well

**LeanPub**

- seems to push the money/"buy this book" a bit harder by always showing a suggested price (even if it's free) in big letters
- only exports as pdf or rbook formats, but not readable as a website
- weird integration with github: need to add LeanPub as a collaborator on the repo
- need to manually "update" the book by clicking a button on their site (vs simply committing)
- creating the book takes several minutes (vs < 1 minute)
- files are .txt extension even though they're markdown files. Not a big deal, just bugged me :)
- I wasn't able to create a book in 2 minutes, after which I gave up because everything else about this website was less pleasant than using gitbooks
- on the plus side: this one looks a bit more professional looking and probably has more reputation

**Comment by npjc** [comment]
:100:

As far as I understand there's no limitation to using both:

1. build w// gitbook
2. push .pdf / .epub to:
  * gitbook
  * leanpub
  * Amazon KDP
  * Apple iBookStore

The key would be figuring out the apis so that this can be scripted where its executed every release kinda thing..

**Comment by npjc** [comment]
Now I find the relevant issue. For future self: STAT545-UBC/Discussion#84
